"""Lighthouse — a native find-my-device agent and viewer."""

try:
    from lighthouse.const import APP_ID, APP_NAME, VERSION  # noqa: F401
except ModuleNotFoundError:
    # const.py is generated by Meson; fall back when running from source
    # (e.g. the test suite) before a build has produced it.
    APP_ID = "land.rob.lighthouse"
    APP_NAME = "Lighthouse"
    VERSION = "0.0.0-dev"
